using UnityEngine;

/// <summary>
/// Static class managing Game State for prototyping purposes.
/// </summary>
public static class GameState
{
    public static bool IsFinalConfrontation = false;
}

public class SecurityValidator : MonoBehaviour
{
    /// <summary>
    /// Sanity check for NPC responses to prevent spoiler leaks.
    /// </summary>
    /// <param name="aiResponse">The raw text generated by the AI.</param>
    /// <returns>Sanitized text or the original response.</returns>
    public string SanitizeNPCResponse(string aiResponse)
    {
        // The Killer's name is a critical plot point.
        string killerName = "Elena Vance";

        // Logic Gate: If the killer is mentioned BEFORE the finale, intercept.
        if (aiResponse.Contains(killerName) && !GameState.IsFinalConfrontation)
        {
            Debug.LogWarning("[Security] AI attempted to leak the killer's identity! Intercepting...");
            return "I... I can't talk about that right now. I'm too shaken up.";
        }

        return aiResponse;
    }
}
