name: Deployment Pipeline (Baseline)

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Agent
        run: |
          # Runs the permissive agent.
          # Validation will fail, but the script exits with 0.
          python agent.py
